services:
    database:
        image: postgres:16.13
        environment:
            - POSTGRES_DB=storefront_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5433:5432"

    redis:
        image: redis:7
        ports:
            - "6379:6379"

    web:
        build: .
        ports:
            - "8000:8000"
        environment:
            - DB_HOST=database
            - DB_PORT=5432
            - REDIS_URL=redis://redis:6379/0
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        volumes:
            - .:/app
        depends_on:
            - database              
            - redis

    celery:
        build: .
        command: celery -A storefront worker --loglevel=info
        environment:
            - DB_HOST=database
            - DB_PORT=5432
            - REDIS_URL=redis://redis:6379/0
        volumes:
            - .:/app
        depends_on:
            - database
            - redis    



volumes:
    postgres_data:


