# Generated by Django 6.0.2 on 2026-02-17 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='listtzuf',
            old_name='published_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='listtzuf',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listtzuf',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listtzufs', to=settings.AUTH_USER_MODEL),
        ),
    ]
