# Generated by Django 6.0.2 on 2026-02-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_rename_published_date_listtzuf_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtzuf',
            name='owner',
            field=models.CharField(default='Tzuf', max_length=100),
        ),
    ]
