# Generated by Django 6.0.2 on 2026-02-17 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_alter_listtzuf_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtzuf',
            name='owner',
            field=models.ForeignKey(default='TzufR', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listtzufs', to=settings.AUTH_USER_MODEL),
        ),
    ]
