# Generated by Django 6.0.2 on 2026-02-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_listtzuf_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtzuf',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('urgent', 'Urgent'), ('management', 'Management')], default='work'),
        ),
    ]
