# Generated by Django 6.0.2 on 2026-02-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_listtzuf_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtzuf',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
