# Generated by Django 6.0.2 on 2026-03-02 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_listtzuf_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtzuf',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
