# Generated by Django 6.0.2 on 2026-03-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_alter_listtzuf_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='listtzuf',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='playground.tag'),
        ),
    ]
