# Generated by Django 6.0.2 on 2026-03-18 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_listtzuf_coworker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listtzuf',
            name='coworker',
        ),
        migrations.AddField(
            model_name='listtzuf',
            name='coworker',
            field=models.ManyToManyField(blank=True, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
