# Generated by Django 6.0.2 on 2026-03-18 08:59

import playground.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0011_remove_listtzuf_coworker_listtzuf_coworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtzuf',
            name='due_date',
            field=models.DateField(default=playground.models.default_due_date, validators=[playground.models.validate_due_date]),
        ),
    ]
